# Generated by Django 3.2.6 on 2021-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210811_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_deparment1', models.CharField(max_length=100)),
            ],
        ),
    ]
