# Generated by Django 3.2.6 on 2021-08-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_details1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details1',
        ),
    ]
